name: Copy File

on:
  push:
    branches:
      - main # Trigger the action on push to the main branch
    paths:
      - 'Dev/TestFile.txt' # Trigger the action only when there is a change committed in the TestFile

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Git user
      run: |
        git config --global user.name "snigdha607"
        git config --global user.email "snigdha.mallapragada@capgemini.com"



    - name: Copy file
      run: |
        cp -r Dev/TestFile.txt QA/
        git add QA/
        git commit -m "Copy TestFile.txt from Dev to QA - $(date +"%Y-%m-%d %H:%M:%S")"
        git push
