name: Copy File

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy file
      run: |
        cp -r Dev/TestFile.txt QA/
        git add QA/
        git commit -m "Move TestFile.txt from Dev to QA"
        git push
