name: Move File

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name "snigdha607"
        git config --global user.email "snigdha.mallapragada@capgemini.com"

    - name: Move file
      run: |
        git mv Dev/TestFile.txt QA/
        git commit -m "Move TestFile.txt from Dev to QA"
        git push
