name: 'Move File'

on:
  push:
    branches: main

jobs:
  move_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Move file
      run: |
        mkidr -p
        
