name: Move File

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move file
        run: mv Dev/TestFile.txt QA

      - name: Commit changes
        run: |
          git add .
          git commit -m "Move file from source to destination"
          git push
