name: 'Move File'

on:
  push:
    branches: 
      - main

jobs:
  move_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Check if only sample file changed
      run: |
        if [ "$(git diff --name-only HEAD~1 HEAD -- Dev/TestFile.txt)" == "Dev/TestFile.txt" ]; then 
          echo "Only sample file changed, moving to QA folder"
          git mv Dev/TestFile.txt QA/TestFile_QA.txt
          git commit -m "Moved sample file to QA folder"
          git push origin main
        else
          echo "Changes detected elsewhere, skipping move"
        fi
