name: 'Move File'

on:
  push:
    branches: 
      -main

jobs:
  move_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Check if only sample file changed
      run: |
        if["$git diff --name-only HEAD~1 HEAD --
        
